force-app/main/default/objects/Saved_Metadata_Entry__c/Saved_Metadata_Entry__c.object-meta.xml
<CustomObject>
    <label>Saved Metadata Entry</label>
    <nameField>
        <displayFormat>SME-{0000}</displayFormat>
        <label>Saved Metadata Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Metadata Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SObject</fullName>
            </value>
            <value>
                <fullName>Non-picklist Field</fullName>
            </value>
            <value>
                <fullName>Picklist Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <label>SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <formula>SObject_Name__c &amp; &quot; - &quot; &amp; Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataCollectorSchedulable.cls
/**
 * Created by Harmath Zsolt on 2025. 03. 01..
 */

public with sharing class MetadataCollectorSchedulable implements Schedulable {
	public Saved_Metadata_Entry__c[] savedMetadataEntries {get; set;}

	public void execute(SchedulableContext context) {
		savedMetadataEntries = new List<Saved_Metadata_Entry__c>();

		// Collect SObjects
		Map<String, SObjectType> globalDescribe = Schema.getGlobalDescribe();
		Set<String> sobjectNames = globalDescribe.keySet();

		for (String sobjectName: sobjectNames) {
			Saved_Metadata_Entry__c savedMetadataEntry = new Saved_Metadata_Entry__c(
				Entity_Name__c = sobjectName,
				Entity_Type__c = 'SObject',
				SObject_Name__c = sobjectName
			);
			savedMetadataEntry.Unique_Key__c = savedMetadataEntry.SObject_Name__c + ' - ' + savedMetadataEntry.Entity_Name__c;
			savedMetadataEntries.add(savedMetadataEntry);
		}

		// Collect Fields

		upsert savedMetadataEntries Unique_Key__c;
	}
}