force-app/main/default/objects/Saved_Metadata_Entry__c/Saved_Metadata_Entry__c.object-meta.xml
<CustomObject>
    <label>Saved Metadata Entry</label>
    <nameField>
        <displayFormat>SME-{0000}</displayFormat>
        <label>Saved Metadata Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Metadata Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SObject</fullName>
            </value>
            <value>
                <fullName>Non-picklist Field</fullName>
            </value>
            <value>
                <fullName>Picklist Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <label>SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <formula>SObject_Name__c &amp; &quot; - &quot; &amp; Entity_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unique Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataCollectorTest.cls
/**
 * Created by Harmath Zsolt on 2025. 03. 01.
 */

@IsTest
private class MetadataCollectorTest {
	@TestSetup static void testFactory() {
		Saved_Metadata_Entry__c sobjectSME = new Saved_Metadata_Entry__c(
			SObject_Name__c = 'Account',
			Entity_Name__c = 'Account',
			Entity_Type__c = 'SObject'
		);
		sobjectSME.Unique_Key__c = sobjectSME.SObject_Name__c + ' - ' + sobjectSME.Entity_Name__c;

		Saved_Metadata_Entry__c fieldSME = new Saved_Metadata_Entry__c(
			SObject_Name__c = 'Account',
			Entity_Name__c = 'Name',
			Entity_Type__c = 'Non-picklist Field'
		);
		fieldSME.Unique_Key__c = fieldSME.SObject_Name__c + ' - ' + fieldSME.Entity_Name__c;

		Saved_Metadata_Entry__c[] smes = new List<Saved_Metadata_Entry__c>{
			sobjectSME,
			fieldSME
		};
		insert smes;
	}

	@IsTest
	static void testBehavior() {
		MetadataCollectorSchedulable schedulable = new MetadataCollectorSchedulable();
		schedulable.execute(null);
	}
}