force-app/main/default/objects/Saved_Metadata_Entry__c/Saved_Metadata_Entry__c.object-meta.xml
<CustomObject>
    <label>Saved Metadata Entry</label>
    <nameField>
        <displayFormat>SME-{0000}</displayFormat>
        <label>Saved Metadata Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Metadata Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SObject</fullName>
            </value>
            <value>
                <fullName>Non-picklist Field</fullName>
            </value>
            <value>
                <fullName>Picklist Field</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>Picklist values, comma separated like: one,two,three</description>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Saved_Metadata_Entry__c/fields/SObject_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Name__c</fullName>
    <label>SObject Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataCollectorFieldsBatchable.cls
/**
 * Created by Harmath Zsolt on 2025. 03. 01.
 */

public with sharing class MetadataCollectorFieldsBatchable implements Database.Batchable<SObject> {
	public Integer sobjectLimit {get; set;}
	public MetadataCollectorFieldsBatchable(Integer sobjectLimit) {
		this.sobjectLimit = sobjectLimit;
	}

	public Database.QueryLocator start(Database.BatchableContext context) {
		if (Test.isRunningTest()) {
			return Database.getQueryLocator([
				SELECT Id
					, SObject_Name__c
					, Entity_Name__c
					, Entity_Type__c
					, Picklist_Values__c
				FROM Saved_Metadata_Entry__c
				WHERE Entity_Type__c = 'SObject'
				LIMIT 1
			]);
		} else return Database.getQueryLocator([SELECT Id, SObject_Name__c, Entity_Name__c, Entity_Type__c, Picklist_Values__c FROM Saved_Metadata_Entry__c	WHERE Entity_Type__c = 'SObject' ORDER BY SObject_Name__c LIMIT :sobjectLimit]);
	}

	public void finish(Database.BatchableContext context) {}

	public void execute(Database.BatchableContext context, List<Saved_Metadata_Entry__c> smes) {
		MetadataCollectorFieldsAsync queueable = new MetadataCollectorFieldsAsync(smes);
		String jobId = System.enqueueJob(queueable);
	}
}